config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  resources :posts do
    member do
      get 'statusState'
    end
  end

  devise_for :users
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
# class ImageUploader < Shrine
# end

app/models/photo.rb
# class Photo < ApplicationRecord
#   include ImageUploader[:image]
# end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [ :edit, :update, :show, :destroy, :statusState ]
  skip_before_action :authenticate_user!, only: :index

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  def statusState
    if @post.status.nil? || @post.status == 'Public'
      @post.status = 'Private'
      @post.save
      flash[:alert] = "Post privé"
      redirect_to post_path(@post)
    else @post.status == 'Private'
      @post.status = 'Public'
      @post.save
      flash[:notice] = "Post public"
      redirect_to post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :content, :photo, :photo_cache, :status)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/page/about.html.erb
about.html.erb

app/views/posts/edit.html.erb
<% if current_user.admin == true %>
  <%= render 'shared/logo' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      <h1>Création d'un post</h1>
        <%= simple_form_for(@post) do |f| %>
          <%= f.input :title, placeholder: "Title", label: false %>
          <!-- <input name="content" id="post_content_trix_input_post" placeholder="HTML content"> -->
          <%= f.trix_editor :content, class: "trix-content", placeholder: "text here..." %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit %>
        <% end %>
          <%= link_to @post, method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          <% end %>
      </div>
    </div>

  </div>
<% else %>
  <%= render 'shared/logo' %>
<% end %>

app/views/posts/index.html.erb
<%= render 'shared/logo' %>
<div class="log">
  <% if current_user %>
    <%= link_to destroy_user_session_path, :method => :delete do %>
      <i class="fa fa-power-off" aria-hidden="true"></i>
    <% end %>

  <% else %>
    <%= link_to new_user_session_path, method: :get do %>
      <i class="fa fa-sign-in" aria-hidden="true"></i>
    <% end %>
  <% end %>
</div>
<%= render 'shared/navbar' %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3 col-xs-12">
      <% @posts.each do |post| %>
            <%= render 'shared/post', post: post %>
      <% end %>
      <div class="bio text-center">
        <div class="photo">
          <%= image_tag "https://media-exp2.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAZqAAAAJDVlZGIxYTM5LTgwNGEtNDY1OC1hNjQ3LWVlMWQ3NjQ4ZjEzMg.jpg", id: "profile_photo" %>
          <p>Dr. Clément Bacle</p>
        </div>
        <div class="text">
          <p>
            <p>Pharmacien passionné par la e-santé et l'entrepreneuriat. </p>
            <p>Je suis convaincu que la santé doit désormais compter sur internet <br> pour mieux servir les patients. </p>
            <p>J'ai cofondé Officina Santé pour donner vie à cet engagement.<br>
            Nous avons construit un programme sur-mesure et intelligent <br> pour permettre à chacun de retrouver son sommeil sans médicament et durablement.</p>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% if current_user.admin == true %>
  <%= render 'shared/logo' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
      <h1>New Post</h1>
        <%= simple_form_for(@post) do |f| %>
          <%= f.input :title, placeholder: "Title", label: false %>
          <!--<input name="content" id="post_content_trix_input_post" placeholder="HTML content">-->
          <%= f.trix_editor :content, class: "trix-content", placeholder: "text here..." %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/logo' %>
<% end %>

app/views/posts/show.html.erb
<%= render 'shared/logo' %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3 col-xs-12">
        <div class="card">
          <div class="card-header">
            <% if @post.photo == nil %>
              <%= cl_image_tag @post.photo, class: "card__image" %>
            <% else %>
              <%= image_tag 'https://static.pexels.com/photos/17663/pexels-photo.jpg', class: "card__image" %>
            <% end %>
            <h2 class="card__title"><%= @post.title %></h2>
          </div>
          <div class="card__text">
            <p><%= sanitize @post.content %></p>
          </div>
          <% if current_user.admin == true %>
            <%= link_to statusState_post_path(@post) do %>
              <% if @post.status.nil? || @post.status == 'Private' %>
                <button input="post[status]" type="button" class="btn btn-warning">Private</button>
              <% else %>
                <button input="post[status]" type="button" class="btn btn-success">Public</button>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<div class="logo">
  <a href="/posts#index">
    <p>HealthCare</p>
  </a>
</div>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="social-media">
        <div class="row">
          <div class="col-xs-3 text-center icon">
            <%= link_to(pages_about_path) do %>
              <i class="fa fa-info" aria-hidden="true" id="info-icon"></i>
            <% end %>
          </div>
          <div class="col-xs-3 text-center icon">
            <a href="https://www.linkedin.com/in/cl%C3%A9ment-b%C3%A2cle-22aa1a100/" target="_blank">
            <i class="fa fa-linkedin" aria-hidden="true" id="linkedin-icon"></i>
            </a>
          </div>
          <div class="col-xs-3 text-center icon">
            <a href="https://www.quora.com/profile/Clement-Bacle" target="_blank">
              <i class="fa fa-quora" aria-hidden="true" id="quora-icon"></i>
            </a>
          </div>
          <div class="col-xs-3 text-center icon">
            <a href="#" target="_blank">
              <i class="fa fa-envelope" aria-hidden="true" id="email-icon"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<div class="card">
  <div class="card-header">
    <% if post.photo == nil %>
      <%= cl_image_tag post.photo, class: "card__image" %>
    <% else %>
      <%= image_tag 'https://static.pexels.com/photos/17663/pexels-photo.jpg', class: "card__image" %>
    <% end %>
    <h2 class="card__title"><%= post.title %></h2>
  </div>
  <div class="card__text">
    <p><%= sanitize post.content %></p>
  </div>
  <div class="share">
    <p class="text-center">SHARE</p>
  </div>
  <% if current_user && current_user.admin == true %>
    <%= link_to edit_post_path(post) do %>
      <i class="fa fa-pencil" aria-hidden="true" id="pencil"></i>
    <% end %>
  <% end %>
</div>